config/routes.rb
Inspirempls::Application.routes.draw do

  match '/auth/:provider/callback' => 'authentications#create'  
  match '/auth/sign_out' => 'authentications#destroy'
  devise_for :users, :controllers => { :registrations => 'registrations' }  
  resources :posts
  resources :authentications
  resources :user
  
  get "splash/index"
  get "/submit", :to => 'site#submit'
  get "/about", :to => 'site#about'
  get "/connect", :to => 'site#connect'
  get "/event", :to => 'site#event'

  match 'tag/:tag', :to => 'tag#show'

  root :to => "posts#index"
  # root :to => "splash#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  require 'open-uri'
  before_validation :download_remote_image, :if => :image_url_provided?
  validates_presence_of :image_remote_url, :if => :image_url_provided?, :message => 'is invalid or inaccessible'
  
  belongs_to :user
  acts_as_taggable
    
  # attr_accessible :image_url, :title, :body, :user_id
  
  cattr_reader :per_page
  @@per_page = 10
  
  has_attached_file :image, 
                    :styles => { :medium => "800x600>", :thumb => "50x50" },
                    :storage => :s3, 
                    :s3_credentials => { :access_key_id => ENV['S3_KEY'],
                                         :secret_access_key => ENV['S3_SECRET'],
                                         :bucket => "images.inspirempls.com" },
                    :path => "/:style/:filename"

  def self.random
    return self.all(:limit => 5, :order => "id DESC")
  end
  
  private
  
    def image_url_provided?
      !self.image_url.blank?
    end

    def download_remote_image
      self.image = do_download_remote_image
      self.image_remote_url = image_url
    end

    def do_download_remote_image
      io = open(URI.parse(image_url))
      def io.original_filename; base_uri.path.split('/').last; end
      io.original_filename.blank? ? nil : io
    rescue # catch url errors with validations instead of exceptions (Errno::ENOENT, OpenURI::HTTPError, etc...)
    end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_filter :get_tags_count, :get_random_posts
  def index
    @posts = Post.paginate(:page => params[:page], :order => 'created_at DESC')
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def new
    if current_user
      @post = current_user.posts.new
    else
      redirect_to posts_path
    end
  end
  
  def create
    @post = current_user.posts.new(params[:post])
    if @post.save
      flash[:notice] = "Successfully created post."
      redirect_to @post
    else
      render :action => 'new'
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      flash[:notice] = "Successfully updated post."
      redirect_to @post
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Successfully destroyed post."
    redirect_to posts_url
  end
end

private

def get_tags_count
  @tags = Post.tag_counts_on(:tags)
end

def get_random_posts
  @random_posts = Post.random
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post, :url => posts_path, :html => { :multipart => true } do |f| %>
  <%= f.error_messages %>
  <fieldset>
    <%= f.text_field :image_url, :value => "Paste image URL or upload an image" %><br/>

    <%= f.file_field :image %><br/>
    
    <%= f.text_field :title, :value => "Title:" %>

    <%= f.text_area :body, :value => "Description:" %>

    <%= f.submit :value => "SUBMIT"%>
  </fieldset>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
  <div class="date">
    <span class="month"><%= post.created_at.strftime("%b") %></span>
    <span class="day"><%= post.created_at.strftime("%d") %></span>
  </div>
  <% if params[:action] == "index" %>
    <a href="<%= post_url(post) %>"><img class="post_image" src="<%= post.image.url(:medium) %>" alt="<%= post.title %>"/></a>
  <% else %>
    <img class="post_image" src="<%= post.image.url(:medium) %>" alt="<%= post.title %>" />
  <% end %>
  <div class="post_content">
    <h3><%= link_to post.title, post_url(post) %></h3>
    <%= post.body %>
    <div class="meta">
      <span class="author">Posted by <%= link_to post.user.name, user_path(post.user.username) %></span>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% title "Edit Post" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @post %> |
  <%= link_to "View All", posts_path %>
</p>

app/views/posts/index.html.erb
<% title "Posts" %>

<div id="posts">
  <% for post in @posts %>
    <%= render :partial => "posts/post", :locals => { :post => post } %>
  <% end %>
</div>

<%= will_paginate @posts %>

<%= link_to "Add Inspiration", new_post_path, :class => "add_btn" %>

app/views/posts/new.html.erb
<% title "New Post" %>

<%= render 'form' %>

<p><%= link_to "Back to List", posts_path %></p>

app/views/posts/show.html.erb
<% title "Post" %>

<%= render :partial => "post", :locals => { :post => @post } %>